swagger: "2.0"
info:
  title: Foo Service
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /foo1:
    post:
      tags:
      - foo
      summary: foo1 foo
      operationId: foo#foo1
      parameters:
      - name: int
        in: body
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
    options:
      tags:
      - foo
      summary: fooOptions foo
      operationId: foo#fooOptions
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /foo2:
    post:
      tags:
      - foo
      summary: foo2 foo
      operationId: foo#foo2
      parameters:
      - name: int
        in: body
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /foo3:
    post:
      tags:
      - foo
      summary: foo3 foo
      operationId: foo#foo3
      parameters:
      - name: int
        in: body
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
